version: '2'
# This Composefile uses named volumes for simplicity. The actual data is saved to /var/lib/docker/volumes/$VOLUME/_data.
# Build args are passed to the Dockerfile to determine the container's purpose.

volumes:
  dionaea-logs:
  slave-logs:

services:
  bro-slave-3:
    build: 
      context: ./mp-ids-bro
      args:
        PURPOSE: slave
    environment:
      - SLAVE_PUBLIC_PORT=9993
      - SLAVE_PUBLIC_IP=138.201.158.43
      - MASTER_PUBLIC_PORT=9999
      - MASTER_PUBLIC_IP=134.100.28.31
    ports:
      - 9993:9999
    command: ["/bro/scripts_slave/"]
    volumes:
      - slave-logs:/usr/local/bro/logs
    depends_on:
      - bro-master

  connector:
    networks:
      - beemaster-demo
    build: ./mp-ids-hp/connector
    command: ["config-uhh.yaml"]

  dionaea:
    networks:
      - beemaster-demo
    build: ./mp-ids-hp/dionaea
    depends_on:
      - connector
    volumes:
      - dionaea-logs:/var/dionaea/logs
    ports:
      - "21:21"
      - "80:80"
      - "443:443"
      - "445:445"
      - "3306:3306"
