version: '2'
# This Composefile uses named volumes for simplicity. The actual data is saved to /var/lib/docker/volumes/$VOLUME/_data.
# Build args are passed to the Dockerfile to determine the container's purpose.

services:
  bro-master:
    networks:
      - beemaster-demo
    build: 
      context: ./mp-ids-bro
      args:
        PURPOSE: master
    command: ["/bro/scripts_master/"]
    volumes:
      - /var/beemaster/log/bro-master:/usr/local/bro/logs

  bro-slave-1:
    networks:
      - beemaster-demo
    build: 
      context: ./mp-ids-bro
      args:
        PURPOSE: slave
    command: ["/bro/scripts_slave/"]
    volumes:
      - /var/beemaster/log/bro-slave-1:/usr/local/bro/logs
    depends_on:
      - bro-master

  bro-slave-2:
    networks:
      - beemaster-demo
    build:
      context: ./mp-ids-bro
      args:
        PURPOSE: slave
    command: ["/bro/scripts_slave/"]
    volumes:
      - /var/beemaster/log/bro-slave-2:/usr/local/bro/logs
    depends_on:
      - bro-master

networks:
  beemaster-demo: