version: '2'
# Build args are passed to the Dockerfile to determine the container's purpose.

services:
  bro-master:
    build:
      context: ./mp-ids-bro
      args:
        PURPOSE: master
    environment:
      - MASTER_PUBLIC_PORT=9999
      - MASTER_PUBLIC_IP=bro-master
    ports:
      - 9999:9999
    volumes:
      - /var/beemaster/log/bro-master:/usr/local/bro/logs

  bro-slave:
    build:
      context: ./mp-ids-bro
      args:
        PURPOSE: slave
    environment:
      - SLAVE_PUBLIC_PORT=9992
      - SLAVE_PUBLIC_IP=bro-slave
      - MASTER_PUBLIC_PORT=9999
      - MASTER_PUBLIC_IP=bro-master
    ports:
      - 9992:9999
    volumes:
      - /var/beemaster/log/bro-slave-2:/usr/local/bro/logs
    depends_on:
      - bro-master
