version: '2'
# This Composefile uses named volumes for simplicity. The actual data is saved to /var/lib/docker/volumes/$VOLUME/_data.
# Build args are passed to the Dockerfile to determine the container's purpose.

services:
  bro-master:
    build:
      context: ./mp-ids-bro
      args:
        PURPOSE: master
    environment:
      - MASTER_PUBLIC_PORT=9999
      - MASTER_PUBLIC_IP=bro-master
    ports:
      - 9999:9999
    volumes:
      - /var/beemaster/log/bro-master:/usr/local/bro/logs

  bro-slave-1:
    build:
      context: ./mp-ids-bro
      args:
        PURPOSE: slave
    environment:
      - SLAVE_PUBLIC_PORT=9999
      - SLAVE_PUBLIC_IP=bro-slave-1
      - MASTER_PUBLIC_PORT=9999
      - MASTER_PUBLIC_IP=bro-master
    ports:
      - 9991:9999
    volumes:
      - /var/beemaster/log/bro-slave-1:/usr/local/bro/logs

  connector:
    build: ./mp-ids-hp/connector
    command: ["config-docker.yaml"]

  dionaea:
    build: ./mp-ids-hp/dionaea
    depends_on:
      - connector
    volumes:
      - /var/beemaster/log/dionaea-logs:/var/dionaea/logs
    ports:
      - "23:23"
      - "53:53/udp"
      - "53:53"
      - "123:123/udp"
      - "21:21"
      - "80:80"
      - "443:443"
      - "445:445"
      - "3306:3306"
