@load ./master_log.bro
@load ./bro_master.bro
@load ./dio_access.bro
@load ./dio_download_complete.bro
@load ./dio_download_offer.bro
@load ./dio_ftp.bro
@load ./dio_mysql_command.bro
@load ./dio_mysql_login.bro
@load ./dio_smb_bind.bro
@load ./dio_smb_request.bro
@load ./dio_blackhole.bro
